//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Philanthropist
    {
        public int Id { get; set; }
        public int FundId { get; set; }
        public string Name { get; set; }
        public int Amount { get; set; }
        public string Message { get; set; }
    
        public virtual Fund Fund { get; set; }
    }
}
